from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.linalg import cho_factor, cho_solve
from scipy.ndimage import gaussian_filter

from cold_recon.data.data_schema import ObservationTable
from cold_recon.operators.support import (
    build_error_covariance,
    build_observation_operator,
)


@dataclass(frozen=True)
class ConditionalGaussianConfig:
    range_cells: tuple[float, float, float] = (6.0, 6.0, 3.0)
    marginal_std: float = 0.15
    conditioning_iterations: int = 20
    conditioning_relaxation: float = 0.85
    correlated_observation_errors: bool = True
    observation_correlation_length: float = 4.0
    direct_correction_fraction: float = 0.35
    lower_bound: float | None = None
    upper_bound: float | None = None


def support_conditioned_gaussian_ensemble(
    prior_mean: np.ndarray,
    observations: ObservationTable,
    grid: dict,
    indices: np.ndarray,
    *,
    n_members: int = 64,
    seed: int = 42,
    config: ConditionalGaussianConfig | None = None,
) -> np.ndarray:
    """Fast support-conditioned Gaussian geostatistical ensemble baseline.

    Correlated unconditional residual fields are generated by Gaussian
    smoothing. Each member is conditioned by covariance-weighted iterative
    support kriging with a fresh draw from the observation-error covariance.
    This is a transparent approximate sequential-Gaussian baseline, not a
    neural model.
    """

    cfg = config or ConditionalGaussianConfig()
    mean = np.asarray(prior_mean, dtype=np.float64)
    support = build_observation_operator(observations, grid, indices=np.asarray(indices, dtype=np.int64))
    observed = observations.values[np.asarray(indices, dtype=np.int64)].astype(np.float64)
    selected = np.asarray(indices, dtype=np.int64)
    covariance = build_error_covariance(
        observations,
        selected,
        correlated=bool(cfg.correlated_observation_errors),
        length_scale=float(cfg.observation_correlation_length),
    )
    factor = cho_factor(covariance, lower=True, check_finite=False)
    error_cholesky = np.linalg.cholesky(covariance)
    row_norm2 = np.asarray(support.matrix.multiply(support.matrix).sum(axis=1)).ravel()
    local_denominator = row_norm2 + np.diag(covariance) / max(
        float(cfg.marginal_std) ** 2, 1.0e-8
    )
    rng = np.random.default_rng(int(seed))
    ensemble = np.empty((int(n_members), *mean.shape), dtype=np.float32)
    for member in range(int(n_members)):
        residual = gaussian_filter(
            rng.normal(size=mean.shape),
            sigma=tuple(float(value) for value in cfg.range_cells),
            mode="reflect",
        )
        residual -= float(np.mean(residual))
        residual *= float(cfg.marginal_std) / max(float(np.std(residual)), 1.0e-8)
        field = mean + residual
        noisy_target = observed + error_cholesky @ rng.normal(size=len(observed))
        for _ in range(int(cfg.conditioning_iterations)):
            mismatch = noisy_target - support.apply(field)
            precision_mismatch = cho_solve(factor, mismatch, check_finite=False)
            covariance_direction = gaussian_filter(
                support.adjoint(precision_mismatch),
                sigma=tuple(float(value) for value in cfg.range_cells),
                mode="reflect",
            )
            direct_direction = support.adjoint(
                mismatch / np.maximum(local_denominator, 1.0e-8)
            )
            direct_fraction = float(np.clip(cfg.direct_correction_fraction, 0.0, 1.0))
            direction = (
                direct_fraction * direct_direction
                + (1.0 - direct_fraction) * covariance_direction
            )
            response = support.apply(direction)
            precision_response = cho_solve(factor, response, check_finite=False)
            denominator = float(response @ precision_response)
            if denominator <= 1.0e-12:
                break
            step = float(mismatch @ precision_response) / denominator
            field = field + float(cfg.conditioning_relaxation) * np.clip(step, -4.0, 4.0) * direction
            if cfg.lower_bound is not None or cfg.upper_bound is not None:
                field = np.clip(field, cfg.lower_bound, cfg.upper_bound)
        ensemble[member] = field.astype(np.float32)
    return ensemble


def support_conditioned_gaussian_ensemble_batched(
    prior_mean: np.ndarray,
    observations: ObservationTable,
    grid: dict,
    indices: np.ndarray,
    *,
    n_members: int = 64,
    seed: int = 42,
    batch_size: int = 8,
    config: ConditionalGaussianConfig | None = None,
) -> np.ndarray:
    """Batched implementation of the support-conditioned Gaussian baseline.

    The statistical model is identical to :func:`support_conditioned_gaussian_ensemble`.
    Members are processed in small batches so sparse support projections and
    Gaussian filtering use matrix-valued operations rather than one Python loop
    per member and conditioning step. Random draws remain independent but are
    not bitwise identical to the scalar implementation for the same seed.
    """

    cfg = config or ConditionalGaussianConfig()
    mean = np.asarray(prior_mean, dtype=np.float64)
    selected = np.asarray(indices, dtype=np.int64)
    support = build_observation_operator(observations, grid, indices=selected)
    observed = observations.values[selected].astype(np.float64)
    covariance = build_error_covariance(
        observations,
        selected,
        correlated=bool(cfg.correlated_observation_errors),
        length_scale=float(cfg.observation_correlation_length),
    )
    factor = cho_factor(covariance, lower=True, check_finite=False)
    error_cholesky = np.linalg.cholesky(covariance)
    row_norm2 = np.asarray(support.matrix.multiply(support.matrix).sum(axis=1)).ravel()
    local_denominator = row_norm2 + np.diag(covariance) / max(
        float(cfg.marginal_std) ** 2, 1.0e-8
    )
    rng = np.random.default_rng(int(seed))
    ensemble = np.empty((int(n_members), *mean.shape), dtype=np.float32)
    spatial_sigma = (0.0, *(float(value) for value in cfg.range_cells))
    direct_fraction = float(np.clip(cfg.direct_correction_fraction, 0.0, 1.0))
    flat_size = int(np.prod(mean.shape))

    for start in range(0, int(n_members), max(int(batch_size), 1)):
        stop = min(start + max(int(batch_size), 1), int(n_members))
        count = stop - start
        residual = gaussian_filter(
            rng.normal(size=(count, *mean.shape)),
            sigma=spatial_sigma,
            mode="reflect",
        )
        residual -= np.mean(residual, axis=(1, 2, 3), keepdims=True)
        residual_std = np.std(residual, axis=(1, 2, 3), keepdims=True)
        residual *= float(cfg.marginal_std) / np.maximum(residual_std, 1.0e-8)
        fields = mean[None, ...] + residual
        noisy_target = observed[:, None] + error_cholesky @ rng.normal(
            size=(len(observed), count)
        )

        for _ in range(int(cfg.conditioning_iterations)):
            flat_fields = fields.reshape(count, flat_size).T
            mismatch = noisy_target - np.asarray(support.matrix @ flat_fields)
            precision_mismatch = cho_solve(factor, mismatch, check_finite=False)
            covariance_adjoint = np.asarray(
                support.matrix.T @ precision_mismatch
            ).T.reshape(count, *mean.shape)
            covariance_direction = gaussian_filter(
                covariance_adjoint,
                sigma=spatial_sigma,
                mode="reflect",
            )
            direct_adjoint = np.asarray(
                support.matrix.T
                @ (mismatch / np.maximum(local_denominator[:, None], 1.0e-8))
            ).T.reshape(count, *mean.shape)
            direction = (
                direct_fraction * direct_adjoint
                + (1.0 - direct_fraction) * covariance_direction
            )
            response = np.asarray(
                support.matrix @ direction.reshape(count, flat_size).T
            )
            precision_response = cho_solve(
                factor, response, check_finite=False
            )
            denominator = np.sum(response * precision_response, axis=0)
            numerator = np.sum(mismatch * precision_response, axis=0)
            active = denominator > 1.0e-12
            if not np.any(active):
                break
            step = np.zeros((count,), dtype=np.float64)
            step[active] = numerator[active] / denominator[active]
            fields = fields + (
                float(cfg.conditioning_relaxation)
                * np.clip(step, -4.0, 4.0)[:, None, None, None]
                * direction
            )
            if cfg.lower_bound is not None or cfg.upper_bound is not None:
                fields = np.clip(fields, cfg.lower_bound, cfg.upper_bound)
        ensemble[start:stop] = fields.astype(np.float32)
    return ensemble
